name: bwrap_static_multiarch_musl
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Bubblewrap source
        uses: actions/checkout@v4
        with:
          repository: containers/bubblewrap
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Compile for all architectures
        run: |
            mkdir -p dist
            # Lista de arquiteturas que você utilizou anteriormente
            for arch in x86_64 aarch64 armhf i386; do
            echo "Compilando para ${arch}..."
            
            # Usamos uma imagem Alpine específica da arquitetura para garantir o musl
            # O mapeamento de nomes de arch do Docker pode variar, 
            # mas 'alpine' com --platform geralmente funciona bem.
            docker run --rm --platform "${arch}" -v $(pwd):/workdir alpine:latest /bin/sh -c "
            # Instala dependências básicas de compilação + libselinux + libcap + xsltproc
            apk add --no-cache build-base meson ninja python3 git libcap-dev libselinux-dev libxslt-dev bash-completion
            cd /workdir
            rm -rf build
            # Configura desabilitando o que não é essencial para o seu build estático,
            # caso queira evitar erros com dependências de testes/documentação
            export CC='gcc'
            export CFLAGS='-static -static-libgcc'
            export LDFLAGS='-static -static-libgcc'
            meson setup build --buildtype=release --default-library=static -Dselinux=disabled -Dman=disabled -Dbash_completion=disabled
            ninja -C build
            cp build/bwrap /workdir/dist/bwrap-${arch}-static"
            done
      - name: Set permissions for dist directory
        run: |
          echo $PATH
          sudo chown -R "$(id -u)":"$(id -g)" dist/
          sudo chmod -R 766 dist/

      - name: Upload artifacts to release
        uses: actions/upload-artifact@v4
        with:
          name: bwrap
          path: 'dist'

      - name: Compute Short SHA
        id: ssha
        run: |
          echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}


  release:
      permissions: write-all
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: bwrap

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous ${{ needs.build.outputs.ssha }}
            automatic_release_tag: ${{ needs.build.outputs.ssha }}
            prerelease: false
            draft: false
            files: |
              *bwrap*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
